doctrine:
    dbal:
        types:
#            coupon_id:  'App\Model\Coupon\Entity\IdType'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/User/Entity/User'
                prefix: 'App\Model\User\Entity\User'
                alias: App4
            RefreshToken:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/RefreshToken/Entity/RefreshToken'
                prefix: 'App\Model\RefreshToken\Entity\RefreshToken'
                alias: RefreshToken
            Coupon:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Coupon/Entity/Coupon'
                prefix: 'App\Model\Coupon\Entity\Coupon'
                alias: Coupon    
            Order:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Order/Entity/Order'
                prefix: 'App\Model\Order\Entity\Order'
                alias: Order 
            Image:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Image/Entity/Image'
                prefix: 'App\Model\Image\Entity\Image'
                alias: Image    
            Feature:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Feature/Entity'
                prefix: 'App\Model\Feature\Entity'
                alias: Feature  
            FeatureValue:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Feature/Entity'
                prefix: 'App\Model\Feature\Entity'
                alias: Feature   
            Product:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Product/Entity'
                prefix: 'App\Model\Product\Entity'
                alias: Feature    
            Cart:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Model/Cart/Entity'
                prefix: 'App\Model\Cart\Entity'
                alias: Feature    

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
